---
title: "LMAnalysis"
author: "Terrence Pope"
date: "5/1/2019"
output: 
  html_document:
    toc: TRUE
    toc_depth: 4
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

for (package in c('devtools', 'plyr', 'tidyverse', 'psych', 'Hmisc', 'reshape2', 'lme4', 'MASS', 'ggplot2', 'gmodels', 'RVAideMemoire', 'phia', 'ggthemes', 'mediation', 'params', 'diagram', 'pander')) {
    if (!require(package, character.only=T, quietly=T)) {
        install.packages(package)
        library(package, character.only=T)
    }
}

dev_mode()

if (!require('ez', character.only=T, quietly=T)) {
    install_github('mike-lawrence/ez')
    library('ez', character.only=T)
}

if (!require('fifer', character.only=T, quietly=T)) {
    install_github("cran/fifer")
    library('fifer', character.only=T)
}

if (!require('processr', character.only=T, quietly=T)) {
    install_github("markhwhiteii/processr")
    library('processr', character.only=T)
}

options(contrasts = c("contr.sum","contr.poly"))

dev_mode()
```

## Load in the data
Let's take a quick peek at our dataset...
```{r Data}

```
